version: "3.9"

services:

  grafana:
    build:
      context: ./grafana_conf
    container_name: Monitoring
    hostname: Monitoring
    restart: unless-stopped
    env_file:
      - ./grafana_conf/.env
    volumes:
      - ./grafana_conf/custom.ini:/etc/grafana/custom.ini                           # Config custom
      - storage:/var/lib/grafana                                                    # Données persistantes
    ports: 
      - "3000:3000"   # Web Grafana
    expose:
      - "9345"        # Port interne uniquement
    networks:
      - pub
      - data

  # prometheus:
  #   image: prom/prometheus:latest
  #   container_name: prometheus
  #   hostname: prometheus
  #   restart: unless-stopped
  #   volumes:
  #     - ./prometheus_conf/prometheus.yml:/etc/prometheus/prometheus.yml  # Config Prometheus
  #     - prometheus_data:/prometheus                      # Données persistantes
  #   command:
  #     - '--config.file=/etc/prometheus/prometheus.yml'
  #     - '--storage.tsdb.path=/prometheus'
  #     - '--web.enable-lifecycle'
  #   expose:
  #     - "9090"
  #   networks:
  #     - data
      
  bot-discord:
    build:
      context: ./grafalertbot_conf
    container_name: GrafAlertBot
    hostname: GrafAlertBot
    env_file:
      - ./grafalertbot_conf/.env
    restart: unless-stopped
    expose:
      - "4000"
    networks:
      - data

networks:
  admin:
    external: true
  pub:
    external: true
  data:
    external: true

volumes:
  storage:
#   prometheus_data:


